# Generated by Django 6.0 on 2025-12-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todoitem",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="todo_images/"),
        ),
    ]
